# Generated by Django 5.0.7 on 2024-09-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_job_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='type',
            new_name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_salary',
        ),
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
