# Generated by Django 5.0.7 on 2024-09-21 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_field', models.FileField(upload_to='muse')),
                ('caption', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
