# Generated by Django 5.0.7 on 2024-09-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_muse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='muse',
            old_name='video_field',
            new_name='video',
        ),
    ]
