# Generated by Django 5.0.7 on 2024-09-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_project_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='add_features',
            new_name='features',
        ),
    ]
