# Generated by Django 5.0.7 on 2024-09-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_alter_project_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
