# Generated by Django 5.0.7 on 2024-09-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_alter_project_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
