# Generated by Django 5.0.7 on 2024-09-16 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_skill_profile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=15)),
                ('job_description', models.TextField()),
                ('business_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(max_length=100)),
                ('apply_type', models.CharField(max_length=100)),
                ('apply_email', models.CharField(blank=True, max_length=100, null=True)),
                ('apply_url', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_type', models.CharField(max_length=100)),
                ('job_salary', models.IntegerField()),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('experience', models.CharField(max_length=100)),
                ('application_deadline', models.DateField()),
                ('career_level', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
