# Generated by Django 5.0.7 on 2024-09-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
