# Generated by Django 5.0.7 on 2024-09-19 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_alter_user_username_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skills'},
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='project_images')),
                ('upload_images', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='project_images')),
                ('description', models.TextField()),
                ('service_title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=100)),
                ('delivery_time', models.DateTimeField()),
                ('revision_number', models.IntegerField(blank=True, null=True)),
                ('add_features', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
