# Generated by Django 5.0.7 on 2024-09-19 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_skills_options_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_field', models.FileField(upload_to='muse')),
                ('caption', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
